___

<a href="https://lms.clarusway.com/course/view.php?id=37"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/3-DVwPY/DVwPy_S06_Capstone_Project%20(Bike%20Store%20Sharing).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="100" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DVwPY_S6/6-DVwPy%20Capstone%20%28Bike%20Store%20Sharing%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="130" height="200" title="Open and Execute in nbviewer"></a><br/>
___

<a href="https://clarusway.com/"><img align="center" src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" alt="CLRSWY" width="450" height="200" title="Welcome to Place Where You can Reinvent Yourself"></a><br/>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:120%; text-align:center; border-radius:10px 10px;">Way to Reinvent Yourself</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [1]:
# YOUR CODE IS HERE

import numpy as np

### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [3]:
# YOUR CODE IS HERE

my_list = np.array([5,10,15,20,25])
my_list

array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [5]:
# YOUR CODE IS HERE

np.zeros((5,5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [6]:
# YOUR CODE IS HERE
np.ones((4,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [8]:
# YOUR CODE IS HERE

np.ones((4,4), dtype = int)*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [9]:
# YOUR CODE IS HERE

np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [11]:
# YOUR CODE IS HERE

np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [12]:
# YOUR CODE IS HERE

np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [18]:
# YOUR CODE IS HERE

np.linspace(0,25,25).reshape(5,5)

array([[ 0.        ,  1.04166667,  2.08333333,  3.125     ,  4.16666667],
       [ 5.20833333,  6.25      ,  7.29166667,  8.33333333,  9.375     ],
       [10.41666667, 11.45833333, 12.5       , 13.54166667, 14.58333333],
       [15.625     , 16.66666667, 17.70833333, 18.75      , 19.79166667],
       [20.83333333, 21.875     , 22.91666667, 23.95833333, 25.        ]])

### 10. Create randomly 5 numbers with numpy.

In [25]:
# YOUR CODE IS HERE

np.random.randint(0,11,5)

array([7, 5, 2, 3, 2])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [26]:
# YOUR CODE IS HERE

np.random.randn(25).reshape(5,5)

array([[-0.87220303, -0.31346729, -1.05439747,  0.27163286, -0.20947569],
       [ 1.2521801 ,  0.6621242 , -0.7625527 , -2.75204262, -1.09876843],
       [-0.78879331,  0.16821471, -2.56659108, -0.38860191, -0.92685706],
       [ 0.60037266, -0.91746364,  0.93551602,  0.61979334,  0.44519348],
       [-1.05259252,  2.25178667, -0.21153546,  1.06314237, -1.79578107]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [27]:
# YOUR CODE IS HERE

np.random.randint(20,50,12).reshape(3,4)

array([[48, 36, 24, 47],
       [41, 25, 40, 38],
       [32, 32, 43, 34]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [40]:
# YOUR CODE IS HERE

ranarr = np.random.randint(0,50,size = (6,8))
ranarr




array([[19, 18, 16, 36, 32, 35, 34, 38],
       [20,  6, 22, 28, 14, 24,  3,  8],
       [28,  4, 42, 17, 40, 42,  5, 23],
       [15, 42, 15, 28, 42,  3, 41,  3],
       [11, 39, 21, 18, 39,  0, 28, 14],
       [ 4, 48, 31,  9, 17,  3, 35, 33]])

In [41]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)

ranarr = np.random.randint(0,50,48).reshape(6,8)
ranarr

array([[13, 44, 35, 31, 23, 39, 19,  6],
       [35, 17, 37, 43,  6, 21, 17,  4],
       [ 0, 31, 31, 26, 23,  7, 12, 13],
       [21,  9, 38, 49, 10, 16,  4,  6],
       [38,  1,  4,  3, 43, 21, 23,  5],
       [17, 42, 19, 43, 10, 28, 49, 19]])

In [42]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr = np.random.randint(0,50,48).reshape(-1,8)
ranarr

array([[26, 43,  8, 30,  0, 27, 19, 46],
       [34, 45, 45, 45, 11, 40, 23, 40],
       [27, 38,  9, 32, 44, 17, 30, 13],
       [10, 19, 26, 16, 29, 48,  7, 22],
       [30,  2, 46,  6,  8, 41, 21, 37],
       [19, 39, 36, 24,  8, 23, 14, 39]])

In [44]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr = np.random.randint(0,50,48).reshape(6,-1)
ranarr


array([[48, 40, 38, 24, 26, 22, 24,  1],
       [ 8,  0, 16, 42, 32, 43, 46, 47],
       [17, 11, 25,  3, 19, 44, 40, 21],
       [45, 25,  2, 39,  8, 11, 25,  1],
       [48, 35, 20, 31,  6, 27, 32, 35],
       [37, 11, 32, 33,  5, 13, 40, 26]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [48]:
# YOUR CODE IS HERE 
mat = np.arange()

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [46]:
# YOUR CODE IS HERE 


### 15. Get the 1st column (index number 0) of the array above.

In [ ]:
# YOUR CODE IS HERE 


### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [ ]:
# YOUR CODE IS HERE 


### 17.Assign 77 to every cell in 3rd column.

In [ ]:
# YOUR CODE IS HERE 


### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [ ]:
# YOUR CODE IS HERE 


### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [ ]:
# YOUR CODE IS HERE 


## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 

# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 



In [ ]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 



### 21. Get the standard deviation (std) of the result above.

In [ ]:
# YOUR CODE IS HERE 



### 22. Get the sum of the 2nd column in the original "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 



In [ ]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 

# YOUR CODE IS HERE 



In [ ]:
# YOUR CODE IS HERE 



### 23. Get the median, mean and std of 3rd column in "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 



In [ ]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 



In [ ]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 



In [ ]:
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 



In [ ]:
# LET US GET MEAN VALUE 

# YOUR CODE IS HERE 



In [ ]:
# LET US GET STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE 



## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [49]:
# YOUR CODE IS HERE 

import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [53]:
# LET US READ Salaries.csv 
df = pd.read_csv("Salaries.csv")
df
# YOUR CODE IS HERE 
df.head()



Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [ ]:
# LET US LOOK AT THE FIRST 5 ROWS 

# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [ ]:
# LET US GET A SAMPLE 

# YOUR CODE IS HERE 



Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [ ]:
# YOUR CODE IS HERE 



In [54]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

# YOUR CODE IS HERE 

df.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [64]:
# YOUR CODE IS HERE 

years = df.value_counts("Year")
years

Year
2014    38123
2013    37606
2012    36766
2011    36159
dtype: int64

In [72]:
df["Year"]

0         2011
1         2011
2         2011
3         2011
4         2011
          ... 
148649    2014
148650    2014
148651    2014
148652    2014
148653    2014
Name: Year, Length: 148654, dtype: int64

In [73]:
df.Year.value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [65]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 
years.size

4

In [66]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 
years.values

array([38123, 37606, 36766, 36159])

In [74]:
df.Year.unique()

array([2011, 2012, 2013, 2014])

### Print out max and avg values in the column of "Totalpay".

In [76]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE 
df.TotalPay.max()


567595.43

In [77]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE 
df.TotalPay.mean()


74768.32197169267

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [79]:
# YOUR CODE IS HERE 

df[df.TotalPay.values > df.TotalPay.mean()]

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [81]:
# YOUR CODE IS HERE 

len(df[df.TotalPay.values > df.TotalPay.mean()])

69489

2

### How much does ALBERT PARDINI make money (including benefits)?

In [115]:
# YOUR CODE IS HERE 

df.loc[df["EmployeeName"] == "ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [128]:
# YOUR CODE IS HERE 
df.loc[df["TotalPayBenefits"] == df["TotalPayBenefits"].min()]["EmployeeName"]

148653    Joe Lopez
Name: EmployeeName, dtype: object

### What are the unique Jobs in dataset?

In [129]:
# YOUR CODE IS HERE 

df.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [131]:
# YOUR CODE IS HERE 

df.JobTitle.value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

### How many people earned more than avg in 2012?

In [149]:
# YOUR CODE IS HERE 

m_2012 = df.loc[df["Year"] == 2012]["TotalPay"].mean()
(df.loc[df["Year"] == 2012]["TotalPay"] > df.loc[df["Year"] == 2012]["TotalPay"].mean())

36159     True
36160     True
36161     True
36162     True
36163     True
         ...  
72920    False
72921    False
72922    False
72923    False
72924    False
Name: TotalPay, Length: 36766, dtype: bool

### How many people have a title of Manager in their jobs?

In [ ]:
# USE APPLY FUNCTION FOR THIS QUESTION!

# YOUR CODE IS HERE 



### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________